### ISSUE TITLE
Meetings 

### ISSUE THREAD

**Issue by ani6gup** [dtextbook/dtextbook.github.io#1]
# 03-13-18

## To-Do 

- [ ] Ask Shang about two parts HTML 
- [ ] Incorporate [turn.js](http://www.turnjs.com/#)
- [ ] Left Side Static, Right Side Interactive 
- [ ] Auto bring up activities 
- [ ] [Django Connection](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/javascript/)

**Comment by ani6gup** [comment]
# 03-27-18 

## ToDo
- [ ] Button / Anchor integrated in the left hand side which opens up a youtube video on the right hand side
- [ ] How to make it scalable? --Having links all stored in one area 
- [ ] API with open functions (openVideo, openAffinityDiagram)
- [ ] Have turn.js be served off of a Django view 
- [ ] Start understanding backend (Django, Realm, Firebase)
